<?php
/**
 * This class has been auto-generated by PHP-DI.
 */
class CompiledContainer extends DI\CompiledContainer{
    const METHOD_MAPPING = array (
  'App\\Service\\DatabaseTestServiceInterface' => 'get1',
  'App\\Service\\IndexServiceInterface' => 'get2',
);

    protected function get1()
    {
        $object = new App\Service\Impl\DatabaseTestService();
        return $object;
    }

    protected function get2()
    {
        $object = new App\Service\Impl\IndexService();
        return $object;
    }

}
